// Simple yes/no dialog
// Copyright © 2009 The University of Chicago
#ifndef VERIFYDIALOG_H
#define VERIFYDIALOG_H

#include <QDialog>
#include "ui_verifydialogbase.h"

#include <QString>
#include <Qt>

class VerifyDialog : public QDialog, private Ui::VerifyDialogBase
{
    Q_OBJECT

public:
	VerifyDialog( QString msg, QWidget* parent = 0,
						Qt::WindowFlags fl = 0 );

protected:

protected slots:
	// Generated by Qt Designer
	void yesSlot();
	void noSlot();
	void cancelSlot();

private:

};

#endif // VERIFYDIALOG_H
